-- Estrutura version-agnostic para comparação de traduções (estilo theWord).
--
-- Desenho: o grego original é tratado como "apenas mais uma tradução"
-- (is_original = true). A chave universal de alinhamento entre versões é o
-- `ref` (OSIS, ex: "John 1:1"), idêntico ao usado em public.verses. Assim o
-- comparador junta versões por `ref` sem acoplar-se a nenhuma tradução
-- específica (Open/Closed: novas versões licenciadas entram só com linhas,
-- sem mudar schema nem código).

-- ── translations ──────────────────────────────────────────────────────────
-- Catálogo de versões disponíveis. PK textual (`code`) para legibilidade nas
-- URLs/queries (ex: 'grc-sblgnt', 'pt-tbl', 'en-web').
create table if not exists public.translations (
  code        text primary key,
  name        text    not null,
  language    text    not null,            -- ISO-ish: 'grc', 'pt', 'en'
  license     text    not null,            -- ex: 'CC BY 4.0', 'Public Domain'
  source_url  text,
  text_type   text,                        -- ex: 'critical', 'textus-receptus', 'translation'
  is_original boolean not null default false,
  sort_order  smallint not null default 0,
  created_at  timestamptz not null default now()
);

-- ── verse_texts ───────────────────────────────────────────────────────────
-- Texto de cada versículo por tradução. Desnormaliza book/chapter/verse para
-- permitir consultas de capítulo eficientes sem join em public.verses (que é
-- específico do corpus grego tokenizado).
create table if not exists public.verse_texts (
  id               bigint generated by default as identity primary key,
  translation_code text     not null references public.translations(code) on delete cascade,
  ref              text     not null,                       -- OSIS: "John 1:1"
  book_id          smallint references public.books(id),
  chapter          smallint not null,
  verse            smallint not null,
  text             text     not null,
  unique (translation_code, ref)
);

-- Lookup de capítulo paralelo: filtra por versão + livro + capítulo, ordena por versículo.
create index if not exists idx_verse_texts_lookup
  on public.verse_texts (translation_code, book_id, chapter, verse);

-- Junção cross-version por `ref` (núcleo do comparador).
create index if not exists idx_verse_texts_ref
  on public.verse_texts (ref);

-- ── RLS: leitura pública (mesmo padrão do corpus) ─────────────────────────
alter table public.translations enable row level security;
alter table public.verse_texts  enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.translations to anon, authenticated;
grant select on public.verse_texts  to anon, authenticated;

drop policy if exists "translations_read" on public.translations;
create policy "translations_read"
  on public.translations
  for select
  to anon, authenticated
  using (true);

drop policy if exists "verse_texts_read" on public.verse_texts;
create policy "verse_texts_read"
  on public.verse_texts
  for select
  to anon, authenticated
  using (true);

-- ── Seed da tradução original (grego) ─────────────────────────────────────
-- A linha do grego SBLGNT é registrada aqui; o backfill dos versículos
-- (concatenação dos tokens) é feito por script ETL em passo separado.
insert into public.translations (code, name, language, license, source_url, text_type, is_original, sort_order)
values (
  'grc-sblgnt',
  'SBL Greek New Testament',
  'grc',
  'CC BY 4.0',
  'https://github.com/Clear-Bible/macula-greek',
  'critical',
  true,
  0
)
on conflict (code) do nothing;
