-- ════════════════════════════════════════════════════════════════════════
--  koine-study — interlinear hebraico (AT)
--  Palavras do WLC com morfologia OSHM por morfema (prefixos + raiz + sufixos).
-- ════════════════════════════════════════════════════════════════════════
--
-- Tabela self-contained, chaveada por localização (book_id, chapter, verse,
-- position) — espelha o estilo de `verse_texts`, sem FK para `verses` (que é
-- só do corpus grego do NT). Cada linha é UMA palavra hebraica; os morfemas
-- (prefixos como ו/ה/ב, a raiz e sufixos pronominais) vivem num array JSONB,
-- porque uma palavra hebraica analisada é multi-morfema — diferente do token
-- grego (1 palavra = 1 lema/morfologia).
--
-- Decisão de modelagem: NÃO reaproveitamos a tabela `tokens` (colunas
-- m_tense/m_voice/m_mood/m_case são gregas; e tokens não comporta sub-morfemas).
-- Hebraico é um domínio distinto → tabela própria (Single Responsibility).
--
-- Cada morfema no JSONB: { s: superfície, l: lema cru, g: strongs|null, m: código OSHM }
-- A decodificação OSHM → análise legível acontece no cliente (lib/hebrew-morph.ts),
-- mantendo o banco enxuto e uma única fonte de verdade para os rótulos.

create table public.hebrew_words (
  id        bigint generated by default as identity primary key,
  book_id   smallint not null references public.books(id),
  chapter   smallint not null,
  verse     smallint not null,
  position  smallint not null,                 -- ordem da palavra no versículo
  surface   text not null,                     -- palavra apontada (RTL, p/ exibição)
  morphemes jsonb not null,                    -- [{ s, l, g, m }]
  unique (book_id, chapter, verse, position)
);
create index hebrew_words_loc_idx on public.hebrew_words (book_id, chapter);

-- Corpus: leitura pública (igual a books/verses/tokens); escrita só via service_role no ETL.
alter table public.hebrew_words enable row level security;
create policy "corpus_read" on public.hebrew_words for select using (true);
