-- ════════════════════════════════════════════════════════════════════════
--  ADR-001 — Pivot do corpus para MACULA Greek (SBLGNT) — Fase D (schema)
--  Migration ADITIVA e não-destrutiva: pode ser aplicada antes do reload.
--    1. Tabela `lexicon_entries` (stack de léxicos em camadas, chaveada por lema)
--    2. `quiz_attempts.token_id` nullable + ON DELETE SET NULL (tokens viram
--       posicionais e instáveis entre edições do texto; o attempt é log histórico)
-- ════════════════════════════════════════════════════════════════════════

-- ╔══════════════════ 1. lexicon_entries (stack em camadas) ══════════════╗
-- Modelo escolhido no ADR-001 (Fase C): tabela normalizada em vez de uma coluna
-- por fonte. Vantagens (Open/Closed): novas fontes (Thayer's, Moulton-Milligan,
-- LSJ) entram como linhas, sem ALTER TABLE; EN e PT coexistem (text_en/text_pt),
-- preservando o original para re-tradução/auditoria. As glosas CURTAS (headword)
-- seguem em lemmas.gloss_en/gloss_pt — esta tabela guarda as ENTRADAS completas.
create table if not exists public.lexicon_entries (
  id         bigint generated by default as identity primary key,
  lemma_id   bigint not null references public.lemmas(id) on delete cascade,
  source     text not null,            -- 'abbott-smith' | 'thayers' | 'moulton-milligan' | 'lsj'
  text_en    text,                     -- entrada original (domínio público / CC BY-SA)
  text_pt    text,                     -- tradução PT (passo translate-lexicon)
  sort_order smallint not null default 0, -- ordem de exibição no painel do leitor
  unique (lemma_id, source)
);
create index if not exists lexicon_entries_lemma_idx on public.lexicon_entries (lemma_id);

comment on table public.lexicon_entries is
  'Stack de léxicos em camadas (ADR-001), chaveada por lema. Uma linha por (lemma_id, source). text_en = original; text_pt = tradução.';

-- RLS: corpus é leitura pública; ninguém escreve via API (só o ETL com service role).
alter table public.lexicon_entries enable row level security;
create policy "corpus_read" on public.lexicon_entries for select using (true);

-- ╔══════════════ 2. quiz_attempts.token_id nullable + SET NULL ══════════╗
-- O reload reatribui ids de tokens (identity) e o SBLGNT diverge do Byzantine,
-- então o token original de um attempt pode deixar de existir. O attempt continua
-- valioso como estatística (acerto/erro + timestamp), então preservamos a linha e
-- apenas soltamos o vínculo: drop NOT NULL + recriar a FK com ON DELETE SET NULL.
alter table public.quiz_attempts
  drop constraint if exists quiz_attempts_token_id_fkey;

alter table public.quiz_attempts
  alter column token_id drop not null;

alter table public.quiz_attempts
  add constraint quiz_attempts_token_id_fkey
    foreign key (token_id) references public.tokens(id) on delete set null;

comment on column public.quiz_attempts.token_id is
  'Token avaliado. Nullable + ON DELETE SET NULL: tokens são posicionais e instáveis entre edições do texto; o attempt sobrevive como log histórico mesmo se o token sumir.';
