-- ════════════════════════════════════════════════════════════════════════
--  koine-study — schema inicial
--  Fase 0: corpus (texto grego + morfologia + léxico) — leitura pública
--  Camada de usuário (SRS, quiz, progresso) — RLS por auth.uid()
-- ════════════════════════════════════════════════════════════════════════

-- ╔══════════════════════ CORPUS (compartilhado, read-only) ══════════════╗

create table public.books (
  id          smallint primary key,          -- ordem canônica (40 = Mateus ... 66 = Apocalipse)
  osis_code   text not null unique,           -- "John", "1John"
  name_pt     text not null,                  -- "João", "1 João"
  name_grc    text,                           -- "ΚΑΤΑ ΙΩΑΝΝΗΝ"
  testament   text not null default 'NT',
  sort_order  smallint not null
);

create table public.lemmas (
  -- "by default": permite inserir o id explícito gerado no build da ingestão
  id            bigint generated by default as identity primary key,
  lemma         text not null,                -- forma de dicionário
  strongs       text,                         -- "G2316"
  gk_number     text,                         -- Goodrick-Kohlenberger
  pos           text,                         -- noun | verb | adjective | ...
  gloss_en      text,                         -- Dodson short gloss
  gloss_long_en text,                         -- Dodson longer gloss
  gloss_pt      text,                         -- traduzido no passo "translate"
  frequency     int not null default 0,       -- ocorrências no corpus
  unique (lemma, strongs)
);
create index lemmas_strongs_idx   on public.lemmas (strongs);
create index lemmas_frequency_idx on public.lemmas (frequency desc);

create table public.verses (
  id        bigint generated by default as identity primary key,
  book_id   smallint not null references public.books(id),
  chapter   smallint not null,
  verse     smallint not null,
  ref       text not null,                    -- "John 1:1"
  unique (book_id, chapter, verse)
);

create table public.tokens (
  id            bigint generated always as identity primary key,
  verse_id      bigint not null references public.verses(id),
  position      smallint not null,            -- ordem na frase
  surface       text not null,                -- forma flexionada (com acentos)
  normalized    text,                         -- sem acentos (para busca)
  lemma_id      bigint references public.lemmas(id),
  strongs       text,
  morph_code    text,                         -- "V-PAI-3S" (código Robinson cru)
  -- campos decodificados (preenchidos pelo morph-decoder na ingestão):
  m_pos         text,
  m_tense       text,
  m_voice       text,
  m_mood        text,
  m_case        text,
  m_number      text,
  m_gender      text,
  m_person      text,
  gloss_context text,                          -- tradução contextual (STEPBible, opcional)
  unique (verse_id, position)
);
create index tokens_lemma_idx on public.tokens (lemma_id);
create index tokens_verse_idx on public.tokens (verse_id);

-- ╔══════════════════════ USUÁRIO (RLS por auth.uid()) ═══════════════════╗

create table public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  plan         text not null default 'free',  -- free | pro
  created_at   timestamptz not null default now()
);

-- Modo Vocabulário (Spaced Repetition — estado FSRS)
create table public.srs_cards (
  id          bigint generated always as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  lemma_id    bigint not null references public.lemmas(id),
  stability   real,
  difficulty  real,
  due_at      timestamptz not null default now(),
  state       text not null default 'new',    -- new | learning | review | relearning
  reps        int not null default 0,
  lapses      int not null default 0,
  last_review timestamptz,
  unique (user_id, lemma_id)
);
create index srs_cards_due_idx on public.srs_cards (user_id, due_at);

-- Modo Parsing (análise morfológica)
create table public.quiz_attempts (
  id            bigint generated always as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  token_id      bigint not null references public.tokens(id),
  question_type text not null,                 -- parse_verb | identify_case | ...
  correct       boolean not null,
  answered_at   timestamptz not null default now()
);
create index quiz_attempts_user_idx on public.quiz_attempts (user_id, answered_at desc);

-- Modo Gramática/Lições (progresso na trilha)
create table public.study_progress (
  id           bigint generated always as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  lesson_id    text not null,
  status       text not null default 'not_started', -- not_started | in_progress | completed
  completed_at timestamptz,
  unique (user_id, lesson_id)
);

-- ╔══════════════════════════════ RLS ════════════════════════════════════╗

-- Corpus: leitura pública (qualquer um lê; ninguém escreve via API)
alter table public.books   enable row level security;
alter table public.lemmas  enable row level security;
alter table public.verses  enable row level security;
alter table public.tokens  enable row level security;

create policy "corpus_read" on public.books  for select using (true);
create policy "corpus_read" on public.lemmas for select using (true);
create policy "corpus_read" on public.verses for select using (true);
create policy "corpus_read" on public.tokens for select using (true);

-- Dados de usuário: cada um só acessa os próprios registros
alter table public.profiles       enable row level security;
alter table public.srs_cards      enable row level security;
alter table public.quiz_attempts  enable row level security;
alter table public.study_progress enable row level security;

create policy "own_profile" on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "own_cards" on public.srs_cards
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own_attempts" on public.quiz_attempts
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own_progress" on public.study_progress
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
